In [1]:
import numpy as np

In [ ]:
a = np.array([1,2,3])
b = np.array([(1+5j,2j,3j), (4j,5j,6j)])
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]]) # 3D array

In [3]:
a

array([1, 2, 3])

In [4]:
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [ ]:
np.mgrid[0:5,0:5] # meshgrid with step 1
np.ogrid[0:2,0:2] # meshgrid with step 1, but only returns slices

(array([[0],
        [1]]),
 array([[0, 1]]))